export const SET_MENU = 'SET_MENU';
export const SET_DIMENSIONS = 'SET_DIMENSIONS';
export const INCREMENT = 'INCREMENT';
export const BACKGROUND = 'BACKGROUND';
export const BACKGROUND_COMPLETE = 'BACKGROUND_COMPLETE';
